project:
  type: website

website:
  title: My analysis
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: yeti
    toc: true

execute:
  freeze: auto
